services:
  - type: web
    name: chainlit-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chainlit run ai.py --port $PORT"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: chatbot-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: chatbot-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: chatbot-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: chatbot-db
          property: password
      - key: GEMINI_API_KEY
        sync: false  # You will enter this manually in the dashboard

databases:
  - name: chatbot-db
    plan: free
